version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c-next-lojinha
    ports:
      - '3036:3000'  # Mapeia a porta 3000 do container para a 3030 no host
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      MYSQL_HOST: db  # Nome do serviço do banco de dados
      MYSQL_USER: root
      MYSQL_PASSWORD: bsi-vendas
      MYSQL_NAME: bsi-vendas
      MYSQL_PORT: 3306  # Porta interna do MariaDB no container
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: c-mysql-lojinha
    environment:
      MYSQL_ROOT_PASSWORD: bsi-vendas
      MYSQL_DATABASE: bsi-vendas  # Cria o banco de dados automaticamente
    ports:
      - "3037:3306"  # Mapeia a porta 3306 do container para a 3031 no host
    volumes:
      - ./data:/var/lib/mysql  # Persiste os dados do banco de dados

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: c-phpmyadmin-lojinha
    environment:
      PMA_HOST: db  # Nome do serviço do banco de dados
    ports:
      - "3038:80"  # Mapeia a porta 80 do container para a 3032 no host
    depends_on:
      - db